name: Move new issues into Backlog

on:
  issues:
    types: [opened]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: Vera 2023-2024
          column: Backlog
          repo-token: ${{ secrets.GITHUB_TOKEN }}
